%     Wiezy = struct(typ, klasa, cialoi, cialoj, sA, sB, phi0, pros, foc, dfoc, ddfoc)
%     'typ',{},... % dopisanych czy kinematyczny - k/d
%     'klasa',{},... % para postepowa czy obrotowa p/o
%           numery cia³ - 1 fiolet, 2 pomarancz, 3 szary, 4 niebieski, 5
%           ³¹cznik, 6 silownik N, 7 silownk M, 8 silownik H, 9 silownik G
%     'bodyi',{},... % numer pierwszego ciala
%     'bodyj',{},... % numer drugiego ciala
%     'sA',{},... % wektor sA w i-tym ukladzie
%     'sB',{},... % wektor sB w j-tym ukladzie
%     'phi0',{},... % kat phi0 (nie dla pary obrotowej)
%     'pros',{},... % wersor prostopadly do osi ruchu w ukladzie jtym (nie dla pary obrotowej)
%     'foc',{},... % funkcja od czasu dla wiezow dopisanych
%     'dfoc',{},... % pochodna funkcji od czasu dla wiezow dopisanych
%     'ddfoc',{}) % druga pochodna funkcji od czasu dla wiezow dopisanych

wspolrzedne;

Tmax = 1.5; % Czas zakonczenia analizy ukladu
dt = 0.01; % Odstep czasowy miedzy mierzonymi punktami

ZakresCzasu = 0:dt:Tmax;
% Wektory sA i sB wyliczone na podstawie powyzszych punktow

sA0O=[O(1);O(2)]; sB2O=[O(1)-c2(1);O(2)-c2(2)];  % Para obrotowa 0-2 ziel-pom
sA2P=[P(1)-c2(1);P(2)-c2(2)]; sB1P=[P(1)-c1(1);P(2)-c1(2)];  % Para obrotowa 1-2 fiol-pom
sA2F=[F(1)-c2(1);F(2)-c2(2)]; sB3F=[F(1)-c3(1);F(2)-c3(2)];  % Para obrotowa 2-3 pom-szar
sA2G=[G(1)-c2(1);G(2)-c2(2)]; sB9G=[G(1)-c9(1);G(2)-c9(2)];  % Para obrotowa 2-9 pom-silownik_2G
sA3E=[E(1)-c3(1);E(2)-c3(2)]; sB10E=[E(1)-c10(1);E(2)-c10(2)];  % Para obrotowa 3-10 bia³o-szare
sA3C=[C(1)-c3(1);C(2)-c3(2)]; sB5C=[C(1)-c5(1);C(2)-c5(2)];  % Para obrotowa 3-5 szary z desk¹
sA1D=[D(1)-c1(1);D(2)-c1(2)]; sB10D=[D(1)-c10(1);D(2)-c10(2)];  % Para obrotowa 1-10 fiol-bial
sA10M=[M(1)-c10(1);M(2)-c10(2)]; sB7M=[M(1)-c7(1);M(2)-c7(2)];  % Para obrotowa 10-7 bial-silownik_1M
sA0N=[N(1)-0.0;N(2)-0.0]; sB6N=[N(1)-c6(1);N(2)-c6(2)];  % Para obrotowa 0-6 ziel-silownik_1N
sA0H=[H(1)-0.0;H(2)-0.0]; sB8H=[H(1)-c8(1);H(2)-c8(2)];  % Para obrotowa 0-8 ziel-silownik_2H
sA1A=[A(1)-c1(1);A(2)-c1(2)]; sB4A=[A(1)-c4(1);A(2)-c4(2)];  % Para obrotowa 1-4 fiol-nieb
sA4B=[B(1)-c4(1);B(2)-c4(2)]; sB5B=[B(1)-c5(1);B(2)-c5(2)];  % Para obrotowa 5-4 niebieski-deska

% daneobrot=[sA0O' sB2O';sA2P' sB1P';sA2F' sB3F';sA2G' sB9G';sA3E' sB10E';sA3C' sB5C';sA1D' sB10D'; sA10M' sB7M'; sA0N' sB6N'; sA0H' sB8H';
%            sA1A' sB4A';sA4B' sB5B'];

Wiezy(1) = cell2struct(...
    {'kinematyczny', 'obrotowy', 0, 2,  sA0O, sB2O, [], [], [], [], [], 'O'}', ...
    fieldnames(Wiezy)); % Punkt O
Wiezy(2) = cell2struct(...
    {'kinematyczny', 'obrotowy', 2, 1,  sA2P, sB1P, [], [], [], [], [], 'P'}', ...
    fieldnames(Wiezy)); % Punkt P
Wiezy(3) = cell2struct(...
    {'kinematyczny', 'obrotowy', 2, 3,  sA2F, sB3F, [], [], [], [], [], 'F'}', ...
    fieldnames(Wiezy)); % Punkt F
Wiezy(4) = cell2struct(...
    {'kinematyczny', 'obrotowy', 2, 9,  sA2G, sB9G, [], [], [], [], [], 'G'}', ...
    fieldnames(Wiezy)); % Punkt G
Wiezy(5) = cell2struct(...
    {'kinematyczny', 'obrotowy', 3, 10,  sA3E, sB10E, [], [], [], [], [], 'E'}', ...
    fieldnames(Wiezy)); % Punkt E
Wiezy(6) = cell2struct(...
    {'kinematyczny', 'obrotowy', 3, 5,  sA3C, sB5C, [], [], [], [], [], 'C'}', ...
    fieldnames(Wiezy)); % Punkt C
Wiezy(7) = cell2struct(...
    {'kinematyczny', 'obrotowy', 1, 10,  sA1D, sB10D, [], [], [], [], [], 'D'}', ...
    fieldnames(Wiezy)); % Punkt D
Wiezy(8) = cell2struct(...
    {'kinematyczny', 'obrotowy', 10, 7,  sA10M, sB7M, [], [], [], [], [], 'M'}', ...
    fieldnames(Wiezy)); % Punkt M
Wiezy(9) = cell2struct(...
    {'kinematyczny', 'obrotowy', 0, 6,  sA0N, sB6N, [], [], [], [], [], 'N'}', ...
    fieldnames(Wiezy)); % Punkt N
Wiezy(10) = cell2struct(...
    {'kinematyczny', 'obrotowy', 0, 8,  sA0H, sB8H, [], [], [], [], [], 'H'}', ...
    fieldnames(Wiezy)); % Punkt H
Wiezy(11) = cell2struct(...
    {'kinematyczny', 'obrotowy', 1, 4,  sA1A, sB4A, [], [], [], [], [], 'A'}', ...
    fieldnames(Wiezy)); % Punkt A
Wiezy(12) = cell2struct(...
    {'kinematyczny', 'obrotowy', 4, 5,  sA4B, sB5B, [], [], [], [], [], 'B'}', ...
    fieldnames(Wiezy)); % Punkt B
Wiezy(13) = cell2struct(...
    {'kinematyczny', 'postepowy', 6, 7,  [-0.2; -0.05], [0.2; 0.05], 0, [-1;4]/sqrt(17), [], [], [], []}', ...
    fieldnames(Wiezy)); % Silownik 1 - MN
Wiezy(14) = cell2struct(...
    {'kinematyczny', 'postepowy', 8, 9,  [-0.05; -0.25], [0.05; 0.25], 0, [-5;1]/sqrt(26), [], [], [], []}', ...
    fieldnames(Wiezy)); % Silownik 2 - GH
Wiezy(15) = cell2struct(...
    {'dopisany', 'postepowy', 6, 7,  [-0.2; -0.05], [0.2; 0.05], 0, [4;1]/sqrt(17), ...
    'l1+a1*sin(omega1*t+phi1)', 'omega1*a1*cos(omega1*t+phi1)', '-omega1*omega1*a1*sin(omega1*t+phi1)', []}', ...
    fieldnames(Wiezy)); % Odcinek NM
Wiezy(16) = cell2struct(...
    {'dopisany', 'postepowy', 8, 9,  [-0.05; -0.25], [0.05; 0.25], 0, [1;5]/sqrt(26), ...
    'l2+a2*sin(omega2*t+phi2)', 'omega2*a2*cos(omega2*t+phi2)', '-omega2*omega2*a2*sin(omega2*t+phi2)', []}', ...
    fieldnames(Wiezy)); % Odcinek HG
